[package]
name = "os-info"
version = "0.1.0"
authors = ["Eli Ma <eli@patch.sh>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
os_info = "*"